apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.13.0
  nodeSets:
  - name: default
    count: 1
    podTemplate:      
      spec:          
        volumes:
        - name: elasticsearch-data
          emptyDir: {} 